#!/bin/sh

# Use the software-only mesa library install in /usr/local/lib as a fallback
# (singularity puts the path to nvidia libraries in LD_LIBRARY_PATH).
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}${LD_LIBRARY_PATH+:}/usr/local/lib
export LD_LIBRARY_PATH

# Source the environment that is defined in the casa-dev images, if it exists.
if [ -f /casa/environment.sh ]; then
    . /casa/environment.sh
fi

# Activate the installation environment if it exists
if [ -f /casa/host/install/bin/bv_env.sh ]; then
    PATH=/casa/host/install/bin:$PATH . /casa/host/install/bin/bv_env.sh
fi

# This script runs the command passed as arguments in a sub-process.
# This is needed to allow it to receive signals.
# The docker main process (pid 1) does not.
"$@"
