#!/bin/sh

# use software mesa
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":/usr/local/lib

# This script runs the command passed as arguments in a different process.
# This is needed to allow it to receive signals.
# The docker main process (pid 1) does not.

"$@"

RETVAL=$?
exit $RETVAL

