#!/bin/bash

set -e
set -x

casaconda="$1"
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$casaconda" ]; then
    echo "Missing destination directory"
    exit 1
fi

if [ ! -e "$casaconda" ]; then
    mkdir "$casaconda"
fi

if [ ! -e "$casaconda/home" ]; then
    mkdir "$casaconda/home"
    for f in .gitconfig .git-credentials; do
        if [ -e "$HOME/$f" ]; then
            cp "$HOME/$f" "$casaconda/home"
        fi
    done
fi

system_image="$casaconda/system"
apptainer="apptainer -s run --containall -B $casaconda:/casa -B /tmp $system_image"
root_apptainer="apptainer run --writable --fakeroot --containall -B $casaconda:/casa -B /tmp $system_image"

if [ ! -e "$system_image" ]; then
    apptainer build --sandbox "$casaconda/system" "$script_dir/apptainer.def"
    cp -a "$script_dir/setup_run_apt" "$casaconda"
    $root_apptainer /casa/setup_run_apt
fi

if [ ! -e "$casaconda/Miniforge3-Linux-x86_64.sh" ]; then
    wget -O "$casaconda/Miniforge3-Linux-x86_64.sh" https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
fi


conda="$apptainer /casa/conda/bin/conda"
if [ ! -e "$casaconda/conda" ]; then
    mkdir "$casaconda/conda"
    $apptainer sh "/casa/Miniforge3-Linux-x86_64.sh" -u -b -p "/casa/conda"
    $conda update conda -y
    cp -a "$script_dir/setup_run_conda" "$casaconda"
    $apptainer /casa/setup_run_conda
    cp -a "$script_dir/setup_dev_conda" "$casaconda"
    $apptainer /casa/setup_dev_conda
fi

cp -a "$script_dir/setup_run_compiled" "$casaconda"
$root_apptainer /casa/setup_run_compiled

if [ ! -e "$casaconda/src" ]; then
    $apptainer git clone https://github.com/sapetnioc/brainvisa-submodules /casa/src
    $apptainer git -C /casa/src submodule update --init --recursive
    cd $casaconda/src
    for d in *; do
        if [ -d "$d" ]; then
            main_branch=$( $apptainer git -C /casa/src/$d branch -r --contains HEAD --format '%(refname)' | grep --invert-match HEAD | python -c 'import sys; print(sys.stdin.read().split("/")[-1])' )
            $apptainer git -C "/casa/src/$d" checkout $main_branch
        fi
    done
fi


# Update all sources
# $apptainer git -C /casa/src submodule foreach git pull

$apptainer /casa/src/brainvisa-cmake/bin/bv_env bash
