#!/bin/sh

export CASA=$( dirname $(readlink -f "$0") )
!/bin/sh

export CASA=$( dirname $(readlink -f "$0") )
export CONDA="$CASA/install"

set -e
set -x

if [ ! -e "$CONDA" ]; then
    . "$CASA/setup_conda"
    $CASA/setup_run_conda
    export BRAINVISA_INSTALL_PREFIX="$CONDA"
    cd "$CASA/build"
    "$CASA/bv_env" make install-runtime
fi
