#!/bin/bash

set -e
set -x

casaconda="$1"
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$casaconda" ]; then
    echo "Missing destination directory"
    exit 1
fi

if [ ! -e "$casaconda" ]; then
    mkdir "$casaconda"
fi

if [ ! -e "$casaconda/home" ]; then
    mkdir "$casaconda/home"
    for f in .gitconfig .git-credentials; do
        if [ -e "$HOME/$f" ]; then
            cp "$HOME/$f" "$casaconda/home"
        fi
    done
fi

system_image="$casaconda/system"
if [ ! -e "$system_image" ]; then
    apptainer build --sandbox "$casaconda/system" "$script_dir/apptainer.def"
fi

if [ ! -e "$casaconda/Miniforge3-Linux-x86_64.sh" ]; then
    wget -O "$casaconda/Miniforge3-Linux-x86_64.sh" https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
fi

apptainer="apptainer run --containall $mounts-B $casaconda:/casa -B /tmp $system_image"
root_apptainer="apptainer run --writable --fakeroot --containall -B $casaconda:/casa -B /tmp $system_image"

conda="$apptainer /casa/conda/bin/conda"
if [ ! -e "$casaconda/conda" ]; then
    mkdir "$casaconda/conda"
    $apptainer sh "/casa/Miniforge3-Linux-x86_64.sh" -u -b -p "/casa/conda"
    $conda update conda -y
fi

for script in setup_run_apt setup_run_conda setup_run_compiled; do
    cp -a "$script_dir/$script" "$casaconda"
    $root_apptainer /casa/$script
done

if [ ! -e "$casaconda/src" ]; then
    $apptainer git clone https://github.com/sapetnioc/brainvisa-submodules /casa/src
    $apptainer git -C /casa/src submodule update --init --recursive
fi

# Update all sources
$apptainer git -C /casa/src submodule foreach ls
