#!/bin/sh

export CASA=$( dirname $(readlink -f "$0") )
export CONDA="$CASA/conda"
export CASA_SRC="$CASA/src"

set -e
set -x

if [ ! -e "$CASA_SRC" ]; then
    mkdir "$CASA_SRC"
    "$CASA/setup_src"
fi



if [ ! -e "$CONDA" ]; then
    . "$CASA/setup_conda"
    ln -s ../../../../recipe/casa-distro_activate.sh "$CONDA/etc/conda/activate.d"
    ln -s ../../../../recipe/casa-distro_deactivate.sh "$CONDA/etc/conda/deactivate.d"
    "$CASA/setup_run_conda"
    "$CASA/setup_run_compiled"
    "$CASA/setup_dev_conda"
fi
