{% set brainvisa = load_file_data(os.path.join(RECIPE_DIR, 'brainvisa.yaml')) %}

package:
  name: brainvisa
  version: {{ brainvisa.version }}

source:
  # url: https://brainvisa.info/download/conda/brainvisa-{{ brainvisa.version }}.tar.xz
  # url: file:///home/yann/casaconda/repository/brainvisa-{{ brainvisa.version }}.tar.xz
  # sha256: {{ brainvisa.sha256 }}
  path: .

build:
  number: 0
  # Build only on linux with Python >= 3.9
  skip: True  # [not linux]
  skip: True  # [py<39]


outputs:
  - name: brainvisa-base
    script: install_brainvisa-base.sh
        
    requirements:
      build:
        - sysroot-conda_2_28-x86_64
        - cmake
        - make
        - pkg-config

      run:
        - sysroot-conda_2_28-x86_64
        - {{ pin_compatible('sysroot_linux-64', max_pin='x.x') }}
        - {{ pin_compatible('libstdcxx-ng', min_pin='x.x', max_pin='x') }}
        - {{ pin_compatible('libgcc-ng', min_pin='x.x', max_pin='x') }}
        - font-ttf-noto-emoji
        - lsb-release
        - matplotlib 3.4.3
        - mesa
        - pyqt
        - qtconsole
        - xorg-libx11
        - pydantic >=1.9
        - redis-py >=4.2
        - nipype
        - dipy
        - pycryptodome
        - cryptography  # needed by populse_mia
        - html2text
        - openpyxl
        - paramiko
        - pillow
        - requests
        - six
        - sqlalchemy
        - traits
        - xmltodict
        - yaml
        - joblib
        - configobj
        - mpi4py
        - nibabel
        - pyparsing
        - pydot
        - pydicom
        - cython
        - xlrd
        - xlwt
        - pandas
        - lark
        - pyzmq
        - ipython
        - nbsphinx
        - sphinx-gallery
        - numpy
        - fastcluster
        - h5py
        - scipy
        - scikit-image
        - pyopengl
        - plotly
        - pcl
        - celery # used by Capsul v3
        - pycryptodome
        - gdk-pixbuf
        - libgfortran5
        - cairo
        - dcmtk
        - libgfortran5
        - mesalib
        - libglib
        - libglu
        - libgomp
        - hdf5
        - libjpeg-turbo
        - jxrlib
        - libllvm14
        - netcdf4
        - openjpeg
        - libpng
        - qwt
        - 'libsigcpp<3'
        - libsvm
        - libtiff
        - libxml2
        - zstd
        - libnetcdf
        - draco
        - pyqtwebkit # or pyqtwebengine ? I do not know which is better.
    about:
      summary: Software base infrastructure for BrainVISA tools
      license: GPL

  - name: brainvisa-data-processing
    script: install_brainvisa-data-processing.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('brainvisa-base', exact=True) }}
    about:
      summary: Data readers/writers and processing tools in C++ and Python
      license: GPL

  - name: anatomist
    script: install_anatomist.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config

      run:
        - {{ pin_subpackage('brainvisa-data-processing', exact=True) }}
    
    about:
      summary: Neuroimaging visualization tool for the BrainVISA project
      license: CeCILL

  - name: brainvisa-disco
    script: install_brainvisa-disco.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
        - {{ pin_subpackage('brainvisa-spm', exact=True) }}
    about:
      summary: Neuroimaging method for cross-subject brain alignment. 
      license: GPL

  - name: brainvisa-spm
    script: install_brainvisa-spm.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
    about:
      summary: Links between SPM and BrainVISA. 
      license: GPL

  - name: brainvisa-freesurfer
    script: install_brainvisa-freesurfer.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
    about:
      summary: Links between Freesurfer and BrainVISA. 
      license: GPL

  - name: brainvisa-cortical-surface
    script: install_brainvisa-cortical-surface.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
    about:
      summary: BrainVISA toolbox providing surface-based generation and processing methods for MR brain data. 
      license: GPL

  - name: brainvisa-highres-cortex
    script: install_brainvisa-highres-cortex.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
    about:
      summary: Analysis of the laminar structure of the cortex in high resolution MRI. 
      license: GPL

  - name: morphologist
    script: install_morphologist.sh
    requirements:
      build:
        - cmake
        - make
        - pkg-config
      run:
        - {{ pin_subpackage('anatomist', exact=True) }}
    about:
      summary: Brain segmentation and sulcal analysis. 
      license: GPL

  # - name: brainrat
  #   script: install_brainrat.sh
  #   requirements:
  #     build:
  #       - cmake
  #       - make
  #       - pkg-config
  #     run:
  #       - {{ pin_subpackage('anatomist', exact=True) }}
  #   about:
  #     summary: 3D histology, reconstruction and analysis. 
  #     license: GPL

  - name: brainvisa
    script: noop.sh
    requirements:
      run:
        - {{ pin_subpackage('brainvisa-base', exact=True) }}
        - {{ pin_subpackage('brainvisa-data-processing', exact=True) }}
        - {{ pin_subpackage('brainvisa-disco', exact=True) }}
        - {{ pin_subpackage('brainvisa-spm', exact=True) }}
        - {{ pin_subpackage('brainvisa-freesurfer', exact=True) }}
        - {{ pin_subpackage('brainvisa-highres-cortex', exact=True) }}
        - {{ pin_subpackage('morphologist', exact=True) }}
        # - {{ pin_subpackage('brainrat', exact=True) }}
    
    about:
      summary: All BrainVISA software
      license: CeCILL

about:
  home: https://brainvisa.info
  license: GPL
  summary: Neuroimaging software platform for mass data analysis
  description: |
    BrainVISA provides a complete, modular, infrastructure for neuroimaging
    software. It helps organizing heterogeneous software and data and
    provides a common general graphical interface for users.
    BrainVISA is thus a set of tools rather than a single software.

