# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: brainvisa-virtualgl
  version: 3.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/VirtualGL/virtualgl
  tag:  ${{ version }}

build:
  # skip:
  #   - win
  #   - osx
  number: 0
  script: |
    cmake -G"Unix Makefiles" "-DCMAKE_INSTALL_PREFIX=$PREFIX" "-DCMAKE_PREFIX_PATH=$CONDA_PREFIX;;$CONDA_PREFIX/x86_64-conda-linux-gnu/sysroot/usr"  "-DCMAKE_REQUIRED_INCLUDES=$CONDA_PREFIX/include;$CONDA_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/include" "-DOPENGL_egl_LIBRARY=$CONDA_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib64/libEGL_mesa.so.0" "$SRC_DIR"
    make -j
    make install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - libjpeg-turbo
    - openjdk
    - xorg-libx11
    - xorg-libxi
    - xorg-libxext
    - mesalib
    - cuda-opencl-dev
    - mesa-libgl-devel-cos7-x86_64
    - mesa-libegl-devel-cos7-x86_64
    - mesa-libglu-devel-cos7-x86_64
    - libstdcxx-ng
    - libxcb
    - libxcb-devel-cos7-x86_64
    - xcb-util-keysyms-devel-cos7-x86_64

tests:
   - script: vglrun

about:
  homepage: https://www.virtualgl.org/
  summary: VirtualGL optimizes remote application performance by intercepting and redirecting OpenGL commands for smoother graphics rendering.
  description: |
    VirtualGL is a versatile toolkit that optimizes the graphical performance of applications running remotely on a server but displayed locally on a client machine. By intercepting OpenGL commands from the remote application and directing them to the client for rendering, VirtualGL enhances responsiveness and efficiency, particularly for graphics-intensive tasks like CAD, scientific visualization, and gaming. This technology enables smoother, more responsive user experiences in remote computing environments by reducing network bandwidth requirements and ensuring high-quality graphics output.
  documentation: https://virtualgl.org/Documentation/Documentation
  repository: https://github.com/VirtualGL/virtualgl

extra:
  recipe-maintainers:
    - BrainVISA team
