#!/bin/sh


installer_url=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
installer=$(echo $installer_url | awk '{split($0, s, "/"); print(s[length(s)])}')
if [ ! -e "$CASA/$installer" ]; then
    wget -O "$CASA/$installer" $installer_url
fi

mkdir "$CONDA"
sh "$CASA/$installer" -u -b -p "$CONDA"
# If mamba is installed
export conda="$CONDA/bin/mamba"
export conda_install="-y"

# Packages always installed in an environment:
#   - mesa-libgl-devel-cos7-x86_64 libglvnd-devel-cos7-x86_64 are necessary
#     to build OpenGL related software such as Anatomist. I do not know if
#     they can be removed (or replaced by non devel package) for a user
#     environement.
"$conda" install -y mesa-libgl-devel-cos7-x86_64 libglvnd-devel-cos7-x86_64
