#!/bin/sh


installer_url=https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
# installer_url=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
# installer_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
installer=$(echo $installer_url | awk '{split($0, s, "/"); print(s[length(s)])}')
if [ ! -e "$CASA/$installer" ]; then
    wget -O "$CASA/$installer" $installer_url
fi

mkdir "$CONDA"
sh "$CASA/$installer" -u -b -p "$CONDA"
if [ -e "$CONDA/bin/mamba" ]; then
    # If mamba is installed
    export conda="$CONDA/bin/mamba"
    export conda_install="-y"
    # Use most recent glibc ABI (the one used by conda-forge to compile Qt)
    "$conda" install -y sysroot-conda_2_28-x86_64
else
    # mamba is not installed
    export conda="$CONDA/bin/conda"
    export conda_install="-y --solver=libmamba"
    # Install packages to use mamba to find packages
    "$conda" install -y -n base conda-libmamba-solver
fi
