#!/bin/sh

export CASA=$( dirname $(readlink -f "$0") )
export CONDA="$CASA/conda"
SRC="$CASA/src"
REPOSITORY="$CASA/repository"

set -e
set -x

if [ ! -e "$REPOSITORY" ]; then
    mkdir "$REPOSITORY"
fi

version=5.2.alpha

cd "$SRC"
components=$( echo * )
components="soma-base soma-workflow soma-io"
tar Jcf "$REPOSITORY/brainvisa-$version.tar.xz" $components
cd "$REPOSITORY"
sha256=$( sha256sum "$REPOSITORY/brainvisa-$version.tar.xz" | awk '{print $1}' )
cat > "$CASA/recipe/brainvisa.yaml" << EOF
version: "$version"
sha256: "$sha256"
EOF

$CASA/conda/bin/mamba build -b--no-anaconda-upload