#!/bin/sh

export CASA="$1"
if [ -z "$CASA" ]; then
    echo "Missing target directory"
    exit 1
fi

export CASA_DISTRO="$2"
if [ -z "$CASA_DISTRO" ]; then
    echo "Missing distro"
    exit 1
fi

export CASA_BRANCH="$3"
if [ -z "$CASA_BRANCH" ]; then
    export CASA_BRANCH=master
fi

export CASA_DISTRO_VERSION="$4"
if [ -z "$CASA_DISTRO_VERSION" ]; then
    export CASA_DISTRO_VERSION="${HOSTNAME}_${USER}_${CASA_BRANCH}"
fi

export CONDA="$CASA/conda"
export CASA_SRC="$CASA/src"
export CASA_DISTRO_SRC="$CASA_SRC/casa-distro"


set -e
set -x

if [ ! -e "$CASA_SRC" ]; then
    mkdir --parents "$CASA_SRC"
    # Temporarily force "conda" branches of some projects
    git -C "$CASA_SRC" clone --branch conda https://github.com/brainvisa/casa-distro
    git -C "$CASA_SRC" clone https://github.com/brainvisa/brainvisa-cmake
fi

if [ ! -e "$CASA/conf" ]; then
    mkdir "$CASA/conf"
    ln -s ../src/casa-distro/setup/conda/bv_maker.cfg "$CASA/conf"
    cat > "$CASA/conf/environment.json" << END_OF_FILE
{
    "CASA_DISTRO": "$CASA_DISTRO",
    "CASA_DISTRO_VERSION": "$CASA_DISTRO_VERSION",
    "CASA_BRANCH": "$CASA_BRANCH"
}
END_OF_FILE
fi


if [ ! -e "$CONDA" ]; then
    . "$CASA/src/casa-distro/setup/conda/setup_conda"
    ln -s ../../../../src/casa-distro/setup/conda/casa-distro_activate.sh "$CONDA/etc/conda/activate.d"
    ln -s ../../../../src/casa-distro/setup/conda/casa-distro_deactivate.sh "$CONDA/etc/conda/deactivate.d"
    "$CASA/src/casa-distro/setup/conda/setup_run_conda"
    "$CASA/src/casa-distro/setup/conda/setup_run_compiled"
    "$CASA/src/casa-distro/setup/conda/setup_dev_conda"
fi

if [ ! -e "$CONDA/mesalib" ]; then
    # For the compilation of OpenGL packages, it is necessary to have include files
    # and dynamic libraries from mesalib packages. However, this package must not
    # be installed otherwise any software using Qt and OpenGL will crash. Therefore,
    # the content of the mesalib package is extracted here and put in "$CONDA/mesalib"
    # directory to be used during compilation but not during execution.
    "$CONDA/bin/mamba" run python "$CASA_SRC/casa-distro/setup/conda/extract_mesalib.py" "$CONDA/mesalib"
fi
