#! /bin/bash

#
# Setup run dependencies with conda
#

set -x
set -e

if [ -e $CONDA/bin/git ]; then
    # if git is installed, we assume that this script has already been
    # executed.
    echo "setup_run_conda already executed => execution canceled"
    exit 0
fi

build_dependencies=(
    # General build dependencies (notably useful for pip-compiled packages)
    gcc
    gxx
    git
    cmake
    make
    patch
    pkg-config

    # Build dependencies of MESA's libGL
 #   #! byacc
 #   flex
 #   #! was libxcb-randr0-dev
 #   libxrandr-devel
 #   llvmdev #? was llvm-dev
 #   meson
 #   mako
    mesa

    # Build dependencies of MIRCen's fork of openslide
    autoconf
    automake
    libtool
    pkg-config  # needed for autoreconf
    openjpeg #? was libopenjp2-7-dev
    libtiff #? was libtiff-dev
    cairo #? was libcairo2-dev
    gdk-pixbuf #? was libgdk-pixbuf2.0-dev
    glib #? was libglib2.0-dev
    libxml2 #? was libxml2-dev
    jxrlib #? was libjxr-dev


    # Build dependencies of SIP/PyQt
#    libqt5svg5-dev  # qtconsole needs PyQt5.QtSvg
#    libqt5opengl5-dev
#    qttools5-dev
#    qtmultimedia5-dev
#    libqt5webchannel5-dev
#    libqt5webkit5-dev
#    libqt5webview5-dev
#    libqt5x11extras5-dev
#    libqt5xmlpatterns5-dev
#    qtwebengine5-dev  # for PyQt

    # Build dependencies of libminc
    hdf5 #? was libhdf5-dev
    libnetcdf #? was libnetcdf-dev

    # Build dependencies for draco
    draco
#    eigen #? was libeigen3-dev


    # Commented-out packages that needs pyqt package in order
    # to avoid an upgrade of sip package. The sip command
    # is only installed with sip package version 4.* but sip
    # package depends on sip 6.*
    pyqt
    qtconsole #? was python3-qtconsole
    'matplotlib==3.4.3'
    #pyqt5-sip
    #'sip=4'
    #qt-main
    #qtconsole-base
    #'matplotlib-base==3.4.3'
)

# Runtime dependencies of FSL
fsl_runtime_dependencies=(
    bc
    #! dc
    libblas #? was libopenblas-base
    tcsh
)

# Runtime dependencies of MATLAB
matlab_runtime_dependencies=(
    lsb-release #? was lsb-core
    #! libxext6
    #! libxt6
    #! libxmu6
)

# Generally useful packages
generally_useful_packages=(
    ca-certificates
    curl
    file
    ipython
    notebook #? was jupyter-notebook  # for interactive Python use
    #! less
    lsb-release
    setuptools  # needed for most source installs with python3-pip
    #! ssh-client  # notably useful for Git repositories over SSH
    #! sudo
    tree
    unzip
    #! wget
    xz #? was xz-utils
    #! lxterminal
    #! lximage-qt
    vim
    #! featherpad
    nano
    openjdk #? was openjdk-11-jre # java is used by some external tools (populse mri_conv...)
    #! openjdk-11-jre-headless
    #! jarwrapper
    #! was java-common
    #! java-wrappers
    font-ttf-noto-emoji #? was fonts-noto-color-emoji
    #! udev
)

# Dependencies of headless Anatomist
headless_anatomist_dependencies=(
    #! mesa-utils
    xorg-libx11 #? was x11-utils
    # xvfb
)

"$conda" install $conda_install ${build_dependencies[@]} ${fsl_runtime_dependencies[@]} ${matlab_runtime_dependencies[@]} ${generally_useful_packages[@]} ${headless_anatomist_dependencies[@]}


pip_installed_dependencies=(
    'pydantic>=1.9'
    'redis-py>=4.2'
    nipype
    dipy
    pycryptodome
    # Matplotlib moved upward due to dependencies with sip
)

pip_packages_runtime_dependencies=(
    click  # dependency of nipype
    isodate  # dependency of nipype
    prov  # dependency of nipype
    simplejson  # dependency of nipype
    tqdm  # dependency of dipy
)

# Python packages needed at runtime by BrainVISA
brainvisa_python_runtime_dependencies=(
    #! python-is-python3

    # python3-crypto  # seems obsolete, not longer available
    cryptography  # needed by populse_mia
    html2text
    #! python3-mysqldb
    openpyxl
    paramiko
    pillow #? was python3-pil  # used in anatomist, morphologist, nuclear_imaging, snapbase
    requests
    six
    sqlalchemy
    traits
    xmltodict
    yaml
    joblib
    configobj
    mpi4py
    nibabel
    pyparsing
    pydot
    pydicom

    cython
    xlrd
    xlwt
    pandas
    lark

    # The following dependencies are installed with pip for various reasons,
    # see install_pip_dependencies.sh.
    #
    # TODO: when upgrading the base system (i.e. switching to Ubuntu 20.04),
    # check that they work when installed with apt.
    #
    pyzmq
    ipython
    #! python3-jupyter-client
    nbsphinx
    sphinx-gallery

    pkgconfig  # TODO: check if necessary for h5py installation
    numpy
    # python3-dipy  # not packaged in APT -> use pip
    fastcluster
    h5py
    scipy
    scikit-image #? was python3-skimage


    # python3-sip
    # python3-pyqt5
    # python3-pyqt5.qtmultimedia
    # python3-pyqt5.qtopengl
    # python3-pyqt5.qtsvg
    # python3-pyqt5.qtwebkit
    # python3-pyqt5.qtsql
    # python3-pyqt5.qtwebsockets
    # python3-pyqt5.qtxmlpatterns
    pyqtwebkit

    pyopengl #? was python3-opengl

    plotly
    pcl

    celery # used by Capsul v3

    pycryptodome

#    python3-torch  # will be installed via pip to get cuda support
#    python3-torchvision
)

brainvisa_shared_library_dependencies=(
    cairo
    dcmtk
    libgfortran5
    mesalib
    libglib
    libglu
    libgomp
    hdf5
    libjpeg-turbo
    jxrlib
    libllvm14
    netcdf4
    openjpeg
    libpng
    qwt
    'libsigcpp<3'
    libsvm
    libtiff
    libxml2
    zstd
)

"$conda" install $conda_install ${pip_installed_dependencies[@]} ${pip_packages_runtime_dependencies[@]} ${brainvisa_python_runtime_dependencies[@]} ${brainvisa_shared_library_dependencies[@]}
