#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import os
import os.path as osp
import sys

binpath = osp.realpath(sys.argv[0])
pypath = osp.join(osp.dirname(osp.dirname(binpath)), 'python')

if not osp.exists(osp.join(pypath, 'casa_distro')):
    branch = os.environ.get('CASA_BRANCH')
    if branch:
        if branch == 'bug_fix':  # fix an obsolete setting
            branch = 'master'
        pypath = '/casa/host/src/development/casa-distro/%s/python' % branch

    if not osp.exists(osp.join(pypath, 'casa_distro')):
        pypath = '/casa/casa-distro/python'

if not pypath or not osp.exists(pypath):
    print('the "%s" command has been called from outside a casa-distro '
          'container. This is not the way it should be used: it must be '
          'called from the within the container.' % osp.basename(sys.argv[0]),
          file=sys.stderr)
    sys.exit(1)

sys.path.insert(0, pypath)

from casa_distro.command import main  # noqa: E402
from casa_distro import container_commands  # noqa: F401, E402

main(meant_for_container=True)
